// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Boglistesystem.Models
{
    [Table("Bog")]
    public partial class Bog
    {
        public Bog()
        {
            BogHolds = new HashSet<BogHold>();
        }

        [Key]
        [Column("Bog_id")]
        public int Bog_id { get; set; }
        [Required]
        [StringLength(256)]
        [Unicode(false)]
        public string Titel { get; set; }
        [Required]
        [StringLength(256)]
        [Unicode(false)]
        public string Forfatter { get; set; }
        public int Udgivelsesår { get; set; }
        [Column("ISBN")]
        public double ISBN { get; set; }
        [Required]
        [StringLength(256)]
        [Unicode(false)]
        public string Billede { get; set; }

        [InverseProperty("Bog")]
        public virtual ICollection<BogHold> BogHolds { get; set; }
    }
}