// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Boglistesystem.Models
{
    [Table("Fag")]
    public partial class Fag
    {
        public Fag()
        {
            Holds = new HashSet<Hold>();
        }

        [Key]
        [Column("Fag_id")]
        public int Fag_id { get; set; }
        [Required]
        [Column("Fag_navn")]
        [StringLength(50)]
        [Unicode(false)]
        public string Fag_navn { get; set; }

        [InverseProperty("Fag")]
        public virtual ICollection<Hold> Holds { get; set; }
    }
}