// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Boglistesystem.Models
{
    [Table("Hold")]
    public partial class Hold
    {
        public Hold()
        {
            BogHolds = new HashSet<BogHold>();
        }

        [Key]
        [Column("Hold_id")]
        public int Hold_id { get; set; }
        [StringLength(30)]
        public string Navn { get; set; }
        [Column("Koordinator_id")]
        public int? Koordinator_id { get; set; }
        [Column("Uddannelse_id")]
        public int? Uddannelse_id { get; set; }
        [Column("Semestre_id")]
        public int? Semestre_id { get; set; }
        [Column("Fag_id")]
        public int? Fag_id { get; set; }
        [Column("Underviser_id")]
        public int? Underviser_id { get; set; }

        [ForeignKey("Fag_id")]
        [InverseProperty("Holds")]
        public virtual Fag Fag { get; set; }
        [ForeignKey("Koordinator_id")]
        [InverseProperty("Holds")]
        public virtual Koordinator Koordinator { get; set; }
        [ForeignKey("Semestre_id")]
        [InverseProperty("Holds")]
        public virtual Semestre Semestre { get; set; }
        [ForeignKey("Uddannelse_id")]
        [InverseProperty("Holds")]
        public virtual Uddannelse Uddannelse { get; set; }
        [ForeignKey("Underviser_id")]
        [InverseProperty("Holds")]
        public virtual Underviser Underviser { get; set; }
        [InverseProperty("Hold")]
        public virtual ICollection<BogHold> BogHolds { get; set; }
    }
}