// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Boglistesystem.Models
{
    [Table("Koordinator")]
    public partial class Koordinator
    {
        public Koordinator()
        {
            Holds = new HashSet<Hold>();
            Undervisers = new HashSet<Underviser>();
        }

        [Key]
        [Column("Koordinator_id")]
        public int Koordinator_id { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string Navn { get; set; }

        [InverseProperty("Koordinator")]
        public virtual ICollection<Hold> Holds { get; set; }
        [InverseProperty("Koordinator")]
        public virtual ICollection<Underviser> Undervisers { get; set; }
    }
}