// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Boglistesystem.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Boglistesystem.Models
{
    [Table("Semestre")]
    public partial class Semestre
    {
        public Semestre()
        {
            Holds = new HashSet<Hold>();
        }

        [Key]
        [Column("Semestre_id")]
        public int Semestre_id { get; set; }
        [Required]
        [StringLength(50)]
        public string Navn { get; set; }

        [InverseProperty(nameof(Hold.Semestre))]
        public virtual ICollection<Hold> Holds { get; set; }
    }
}