// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Boglistesystem.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Boglistesystem.Models
{
    [Table("Uddannelse")]
    public partial class Uddannelse
    {
        public Uddannelse()
        {
            Holds = new HashSet<Hold>();
        }

        [Key]
        [Column("Uddannelse_id")]
        public int Uddannelse_id { get; set; }
        [Required]
        [Column("Uddannelse_navn")]
        [StringLength(50)]
        public string Uddannelse_navn { get; set; }

        [InverseProperty(nameof(Hold.Uddannelse))]
        public virtual ICollection<Hold> Holds { get; set; }
    }
}