// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Boglistesystem.Models
{
    [Table("Underviser")]
    public partial class Underviser
    {
        public Underviser()
        {
            Holds = new HashSet<Hold>();
        }

        [Key]
        [Column("Underviser_id")]
        public int Underviser_id { get; set; }
        [Required]
        [StringLength(30)]
        public string Navn { get; set; }
        [Required]
        [StringLength(10)]
        public string Initialer { get; set; }
        [Column("Koordinator_id")]
        public int? Koordinator_id { get; set; }

        [ForeignKey(nameof(Koordinator_id))]
        [InverseProperty("Undervisers")]
        public virtual Koordinator Koordinator { get; set; }
        [InverseProperty(nameof(Hold.Underviser))]
        public virtual ICollection<Hold> Holds { get; set; }
    }
}